### ISSUE TITLE
Broken in Ansible 2.4

### ISSUE THREAD

**Issue by dlundgren** [dlundgren/ansible-plugins#1]
The modules that use the configuration are currently broken
```The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 88, in run
    items = self._get_loop_items()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 216, in _get_loop_items
    items = mylookup.run(terms=loop_terms, variables=self._job_vars, wantlist=True)
  File "/home/ansible/ops/library/lookup_plugins/available_vars_files.py", line 29, in run
    paths = self.get_paths(variables)
  File "/home/ansible/ops/library/lookup_plugins/available_vars_files.py", line 51, in get_paths
    lookupPaths = C.get_config(C.p, C.DEFAULTS, 'lookup_vars_paths', None, [], value_type='list')
AttributeError: 'module' object has no attribute 'p'```

**Comment by dlundgren** [comment]
According to https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/porting_guide_2.4.rst I need refactor how the configuration is obtained.
